blank_issues_enabled: false
contact_links:
  - name: â“Questions about how to use this library?
    url: https://stackoverflow.com/questions/tagged/react-native-picker-select
    about: Please read the documentation thoroughly, search through existing issues, and then ask any lingering questions on StackOverflow.
