blank_issues_enabled: false
contact_links:
  - name: â“Questions about how to use this library?
    url: https://stackoverflow.com/questions/tagged/react-native-picker-select
    about: Please ask and answer questions here.
